### ISSUE TITLE
Build error on NodeJS v12

### ISSUE THREAD

**Issue by Wandalen** [alirdn/node-windows-kill#1]
Hello! Seems build on later versions of NodeJS is broken. 

```
> windows-kill@0.3.3 install-native D:\work\wExternalFundamentals\node_modules\windows-kill
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/alirdn/node-windows-kill/releases/download/0.3.3/windows-kill-v0.3.3-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for windows-kill@0.3.3 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  windows-kill-library.cpp
  signal.cpp
  sender.cpp
  ctrl-routine.cpp
  remote-process.cpp
  stdafx.cpp
  node-windows-kill.cpp
  win_delay_load_hook.cc
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(23): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [D:\work\wExternalFundamentals\
node_modules\windows-kill\build\windows-kill.vcxproj]
  c:\users\fov\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: see declaration of 'v8::Value::NumberValue' (compiling source file ..\src\node-windows-kill.cpp)
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(24): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [D:\work\wExternalFundamentals\
node_modules\windows-kill\build\windows-kill.vcxproj]
  c:\users\fov\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2608): note: see declaration of 'v8::Value::NumberValue' (compiling source file ..\src\node-windows-kill.cpp)
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(72): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [D:\work\wExternalFu
ndamentals\node_modules\windows-kill\build\windows-kill.vcxproj]
  c:\users\fov\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\node-windows-kill.cpp)
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(71): error C2661: 'v8::Object::Set': no overloaded function takes 1 arguments [D:\work\wExternalFundamentals\n
ode_modules\windows-kill\build\windows-kill.vcxproj]
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(74): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [D:\work\wExternalFu
ndamentals\node_modules\windows-kill\build\windows-kill.vcxproj]
  c:\users\fov\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5995): note: see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\node-windows-kill.cpp)
d:\work\wexternalfundamentals\node_modules\windows-kill\src\node-windows-kill.cpp(73): error C2661: 'v8::Object::Set': no overloaded function takes 1 arguments [D:\work\wExternalFundamentals\n
ode_modules\windows-kill\build\windows-kill.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `E:\VisualStudio\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fov\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fov\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\work\\wExternalFundamentals\\node_modules\\windows-kill\\lib\\binding\\windows-kill.node" "--module_name=windows-kill" "--module_path=D:\\work\\wExternalFundamentals\\node_modules\\windows-kill\\lib\\binding" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd D:\work\wExternalFundamentals\node_modules\windows-kill
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\fov\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\work\wExternalFundamentals\node_modules\windows-kill\lib\binding\windows-kill.node --module_name=windows-kill --module_path=D:\work\wExternalFundamentals\node_modules\windows-kill\lib\binding --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work\wExternalFundamentals\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work\\wExternalFundamentals\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\work\wExternalFundamentals\node_modules\windows-kill
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\fov\AppData\Roaming\nvm\v12.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\work\wExternalFundamentals\node_modules\windows-kill\lib\binding\windows-kill.node --module_name=windows-kill --module_path=D:\work\wExternalFundamentals\node_modules\windows-kill\lib\binding --napi_version=5 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-kill@0.3.3 install-native: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-kill@0.3.3 install-native script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fov\AppData\Roaming\npm-cache\_logs\2019-12-11T13_25_58_160Z-debug.log
D:\work\wExternalFundamentals\node_modules\windows-kill\scripts\install.js:10
        throw new Error('An issue occured during installing native module.');
        ^
Error: An issue occured during installing native module.
    at Object.<anonymous> (D:\work\wExternalFundamentals\node_modules\windows-kill\scripts\install.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-kill@0.3.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-kill@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fov\AppData\Roaming\npm-cache\_logs\2019-12-11T13_25_58_259Z-debug.log
```

**Comment by ElyDotDev** [comment]
@Wandalen Thanks for reporting. I will fix it asap.

**Comment by Wandalen** [comment]
Here is fix. Please accept the PR.

https://github.com/alirdn/node-windows-kill/compare/master...volodymyrmigdal:master

**Comment by ElyDotDev** [comment]
Great. I was working on it and fixed it. Why you changed the name into `wwindowskill`?

**Comment by ElyDotDev** [comment]
Thanks for your contribution, will merge it.

**Comment by Wandalen** [comment]
It was temporary fix. We didn't know when you will fix that, so we made a fork and changed name to publish the fork.

**Comment by vmihdal** [comment]
Hello! I created a [pull request](https://github.com/alirdn/node-windows-kill/pull/2) that fixes problem with running [npm test](https://ci.appveyor.com/project/alirdn/node-windows-kill/builds/29532450#L65) command. Can you please accept the pr and publish fix for problem with node v12?
